spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://164.68.125.91:5449/moteur_remuneration
    username: globalperf
    password: GlobalPerf@2024
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
